// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BWjZgmc9_65G5bNmbLashwQii7jf1tI',
    appId: '1:580876700157:web:2195ca65a92e9b42357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    authDomain: 'tearberg-8fba6.firebaseapp.com',
    databaseURL: 'https://tearberg-8fba6-default-rtdb.firebaseio.com',
    storageBucket: 'tearberg-8fba6.appspot.com',
    measurementId: 'G-Q3CYN7EHLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKbewoE-bOG3tyy-5Hx474voZ81X2MJc',
    appId: '1:580876700157:android:97da481a7ca3e790357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    databaseURL: 'https://tearberg-8fba6-default-rtdb.firebaseio.com',
    storageBucket: 'tearberg-8fba6.appspot.com',
  );
}
